---
- name: Install required packages
  apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - python-libvirt
      - python-lxml
      - bridge-utils
      - cloud-image-utils
      - virtinst

- name: Libvirtd systemd service
  service:
    name: libvirtd
    enabled: true
    state: started

# Manage cloud image
- name: qemu images directory
  file:
    state: directory
    path: /virt/images

- name: Check Ubuntu cloud image
  uri:
    url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
    method: HEAD
  register: cloudimg_http_stat
  check_mode: false

- name: Check local cloud image
  stat:
    path: /virt/images/bionic-server-cloudimg-amd64.img
    get_checksum: false
  register: cloudimg_local_stat

- name: Update Ubuntu cloud image
  get_url:
    url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
    dest: /virt/images/bionic-server-cloudimg-amd64.img
  when: not cloudimg_local_stat.stat.exists or
        cloudimg_local_stat.stat.size != cloudimg_http_stat.content_length
  register: cloudimg_local_updated

# VM Directory
- name: Virtual machine directory
  file:
    path: /virt/vms
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Configure Virtual Machines
  include_tasks: vm.yml
  loop: "{{ virtual_machines }}"
  loop_control:
    loop_var: vm

- name: "Copy private key"
  copy:
    src: vm_key
    dest: "/home/ubuntu/.ssh/vm_key"
    mode: 0600
