---
- name: Launch vm
  hosts: hosts
  become: true 
  roles: 
    - role: libvirt
      vars:
        virtual_machines:
        - name: test
          memory: 2048
          vcpu: 2
        vhostusers:
        - mac: 00:00:00:00:00:01
          path: /tmp/dpdkvhostclient0

      
